### ISSUE TITLE
Linked Demo not working in Chrome

### ISSUE THREAD

**Issue by elbotho** [nuxodin/svgEditable#2]
Not really a problem, but the online demo is broken in chrome. Works in Firefox.
Also works in Chrome locally.

Error messages:
![error screenshot](https://cloud.githubusercontent.com/assets/1258870/6021790/a2072ef6-abb8-11e4-87ff-1519e8ce7df7.png)

**Comment by nuxodin** [comment]
The new link is working:
rawgit.com/nuxodin/svgEditable/master/tests/index.htm

**Comment by elbotho** [comment]
nice.
